POST http://localhost:3000/api/login
Content-Type: application/json

{
  "username": "admin",
  "password": "1234"
}

###

@authorizationToken = fec42666f8dcd0f2ca89219d0574ce6935b30dff912911aa78bc26603f917270

GET http://localhost:3000/api/users
Authorization: Bearer {{authorizationToken}}

###

POST http://localhost:3000/users
Authorization: Bearer {{authorizationToken}}
Content-Type: application/json

{
  "username": "ale2",
  "password": "123456",
  "displayName": "Juan Pérez",
  "email": "juan.perez@example.com"
}