GET http://localhost:3000/users

###

POST http://localhost:3000/users
Content-Type: application/json

{
  "username": "Juan",
  "password": "12345",
  "displayName": "Juan Pérez",
  "email": "juan.perez@example.com"
}